### ISSUE TITLE
How to make simple DLNA audio player?

### ISSUE THREAD

**Issue by skylai82** [yellobyte/ESP32-Webradio-PlusDLNA#3]
Is this posible using ESp32-s2 to make it DLNA audio player?

**Comment by yellobyte** [comment]
The project builds without errors for ESP32/ESP32-S2/ESP32-S3.

**Comment by skylai82** [comment]
> The project builds without errors for ESP32/ESP32-S2/ESP32-S3.

Can you share a simple DLNA code?  ：） I want stream my phone Music player to DLNA  ESP32 speaker.

**Comment by yellobyte** [comment]
Sorry, I don't get what you want exactly....

**Comment by skylai82** [comment]
> Sorry, I don't get what you want exactly....
Make my ESP32-S2 + MAX98357A like product below.
https://www.amazon.com/AudioCast-Receiver-Airmusic-Wireless-Supported/dp/B09C1ZS1L3/ref=sr_1_3?keywords=dlna+receiver&qid=1701537604&sr=8-3

![Screenshot from 2023-12-03 01-21-33](https://github.com/yellobyte/ESP32-Webradio-PlusDLNA/assets/37041202/1bc6b240-e6ed-4fe5-bfb2-03202f856d85)

**Comment by yellobyte** [comment]
You want to receive audio from a dlna server with ESP32, send it to a MAX98357A and play it via loudspeaker ?

**Comment by skylai82** [comment]
> You want to receive audio from a dlna server with ESP32, send it to a MAX98357A and play it via loudspeaker ?

Yes, it this possible? :)

**Comment by yellobyte** [comment]
yes

**Comment by skylai82** [comment]
> yes

Where can I find the simple code? 
：）

**Comment by yellobyte** [comment]
Unfortunately life is not that easy as you might think... :-) ...technically of course it's possible but I doubt there is a piece of SW lying around that perfectly fits your needs ...the simple code... DLNA-Server--(UPnP)-->ESP32--(I2S)-->MAX98357A. You just have to write it yourself which then requires time & efforts. You could integrate a small LCD display and some buttons as well...if you have a few weekends to spare...

**Comment by skylai82** [comment]
> Unfortunately life is not that easy as you might think... :-) ...technically of course it's possible but I doubt there is a piece of SW lying around that perfectly fits your needs ...the simple code... DLNA-Server--(UPnP)-->ESP32--(I2S)-->MAX98357A. You just have to write it yourself which then requires time & efforts. You could integrate a small LCD display and some buttons as well...if you have a few weekends to spare...

Yes, I think so too, it's not that easy, I can't find anyone sharing the code online. :)

https://github.com/yellobyte/ESP32-Webradio-PlusDLNA/assets/37041202/97f5ecc3-3f73-4474-a40b-5eaf9e3aa88b
My unique internet radio + waiting DLNA receiver function.  :)

**Comment by yellobyte** [comment]
It is online: https://github.com/yellobyte/ESP32-Webradio-PlusDLNA/tree/main/Software/src  Feel free to take it as a starting point.

**Comment by skylai82** [comment]
> It is online: https://github.com/yellobyte/ESP32-Webradio-PlusDLNA/tree/main/Software/src Feel free to take it as a starting point.

Thanks！ I will try to simplify code to my Internet Radio.
I've seen it before, but it's quite complicated for a beginner like me. ：）
Good Night.

**Comment by yellobyte** [comment]
Have fun !
